### ISSUE TITLE
Error: The paths '-1' are not writeable.

### ISSUE THREAD

**Issue by Hasnep** [DesiQuintans/librarian#21]
After updating to R 3.5.3 I get the following error when using `librarian::shelf`:

```
librarian::shelf(tidyverse)
#> Error in lib_paths(lib, make_path = TRUE, ask = ask): 
#>   The paths
#> 
#>   '-1'
#> 
#>   are not writeable.
```

My `lib_paths` are:

```
librarian::lib_paths()
#> [1] "C:/Users/Hannes/Documents/R/win-library/3.5"
#> [2] "C:/Program Files/R/R-3.5.3/library"
```

Is this a problem with my libpaths or with the librarian package?

Thanks

**Comment by DesiQuintans** [comment]
Hi, sorry for the late reply, this did not arrive in my email for some reason. I'm unable to replicate this on my machine with either R 3.5.3 or R devel.

However, I've just merged a fix from @milescsmith who had the same issue as you. Can you please reinstall from GitHub `remotes::install_github("DesiQuintans/librarian")` and let me know if that solves the problem for you too?

**Comment by Hasnep** [comment]
Works perfectly now, thank you!

**Comment by jameshunterbr** [comment]
Sorry, but this has popped up again with a Windows 10 installation:

`Error in lib_paths(lib, make_path = TRUE, ask = ask) : The paths '-1' are not writeable.
`
lib paths:

> librarian::lib_paths()
[1] "C:/Users/james/OneDrive/Documents/R/win-library/3.6"
[2] "C:/Program Files/R/R-3.6.2/library"  

The calling command: 
librarian::shelf(here, readxl,  glue, tidyverse, knitr, kableExtra, ggpubr,
                 CGPfunctions, janitor, summarytools, deSolve)

The traceback text goes directly from the call to the stop line in your shelf function.

Could you have another look at the "paths '-1'" part of this. I don't understand why it's seeing a path with that text.

thanks,

Jim Hunter

**Comment by GitHunter0** [comment]
I'm having the same issue but the Github version solved

**Comment by psyguy** [comment]
I'd like to second this issue: The CRAN package throws that error but the GitHub version solves it.

**Comment by GitHunter0** [comment]
Hi @DesiQuintans , do you have an estimate date when you are going to update CRAN version?

**Comment by tungmilan** [comment]
+1 for CRAN release asap as I also have this problem

**Comment by DesiQuintans** [comment]
Sorry that this one took me so long to get around to. I have just submitted v1.8.0 to CRAN which includes the fixed code from GitHub.

**Comment by tungmilan** [comment]
Thanks @DesiQuintans ! Are you getting the updated version to CRAN soon?

**Comment by DesiQuintans** [comment]
> 
> 
> Thanks @DesiQuintans ! Are you getting the updated version to CRAN soon?

It's finally up now :)
