### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [DesiQuintans/librarian#3]
Hello @DesiQuintans 

I am a graphic designer. I make logo contributions to open source software. 

I designed a logo for librarian. If you like it, i will send a pr. What do you think the logo?

![librarian](https://user-images.githubusercontent.com/36298335/42735077-fd6a3f3a-8856-11e8-8be8-beac173a1a00.jpg)

**Comment by DesiQuintans** [comment]
Hi reallinfo, sorry for the delay in replying. I would be grateful if you contributed a logo, but I don't think this one communicates the package very well. To me, the big draw of librarian is that you can ask it to gather many different packages from many different places and it will just *do it*, and it would be great to visually communicate that idea.
